# ── Secrets, stored properly (no passwords in code) ───────────
# JWT signing secrets are GENERATED by Terraform — they exist only in
# state and Secrets Manager, never in any source file. Supabase creds
# come from sensitive variables (gitignored tfvars / TF_VAR_* env).
# Everything is written to AWS Secrets Manager as the system of record.

resource "random_password" "jwt_access" {
  length  = 64
  special = false
}

resource "random_password" "jwt_refresh" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "app" {
  name        = "${var.project}/app"
  description = "TaskFlow application secrets (Supabase + JWT)."

  # Secrets Manager normally SCHEDULES deletion with a recovery window, which
  # would leave the name reserved and make the next `apply` fail with
  # "already scheduled for deletion". 0 = delete immediately, so
  # `terraform destroy` then `terraform apply` reliably rebuilds from scratch.
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id = aws_secretsmanager_secret.app.id
  secret_string = jsonencode({
    SUPABASE_URL       = var.supabase_url
    SUPABASE_ANON_KEY  = var.supabase_anon_key
    JWT_ACCESS_SECRET  = random_password.jwt_access.result
    JWT_REFRESH_SECRET = random_password.jwt_refresh.result
  })
}
