variable "project" {
  description = "Name prefix for all resources."
  type        = string
  default     = "taskflow"
}

variable "aws_region" {
  description = "AWS region (any value works for LocalStack)."
  type        = string
  default     = "us-east-1"
}

variable "localstack_endpoint" {
  description = "LocalStack edge endpoint."
  type        = string
  default     = "http://localhost:4566"
}

variable "docker_host" {
  description = "Docker daemon host. Windows named pipe by default; use unix:///var/run/docker.sock on Linux/macOS."
  type        = string
  default     = "npipe:////./pipe/docker_engine"
}

# ── External Supabase (database) — supplied, never hardcoded ──
# These are the ONLY secrets you provide; they live in a gitignored
# terraform.tfvars or TF_VAR_* env vars, and Terraform stores them in
# Secrets Manager. The JWT secrets are generated by Terraform (see
# secrets.tf), so they never appear in any file at all.
variable "supabase_url" {
  description = "Supabase project URL."
  type        = string
  sensitive   = true
}

# The BACKEND must run on the SERVICE-ROLE key. With NODE_ENV=production the
# app (src/config/env.js) refuses to start on the anon key, so providing only
# the anon key here crash-loops the api/worker containers. Required.
variable "supabase_service_role_key" {
  description = "Supabase service-role key (server-side; required in production)."
  type        = string
  sensitive   = true
}

# Anon/publishable key is optional and unused by the backend (kept only so it
# can be stored alongside the others if you want it). Defaults to empty.
variable "supabase_anon_key" {
  description = "Supabase anon/publishable key (optional; not used by the backend)."
  type        = string
  sensitive   = true
  default     = ""
}

# ── App configuration ────────────────────────────────────────
variable "api_image" {
  description = "Pre-built app image tag (built by CI / `docker build -t taskflow-api:tf ./backend`)."
  type        = string
  default     = "taskflow-api:tf"
}

variable "api_port" {
  description = "Host port to expose the API on."
  type        = number
  default     = 3001
}

variable "node_env" {
  description = "NODE_ENV for the app containers."
  type        = string
  default     = "production"
}

variable "cors_origin" {
  description = "Allowed CORS origin for the API."
  type        = string
  default     = "http://localhost:5173"
}
